# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20171014_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='internetarchive_batch_id',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
