# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_screenshot_internetarchive_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='internetarchive_crop_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='internetarchive_image_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
